pipelines:
  default:
    # Test with Maven/H2
    - step:
        name: Test with Maven/H2
        script: 
          - cd todobackend
          - mvn test -Dspring.profiles.active=dev
        caches: 
          - maven
          
    # Test with Maven/PSQL
    - step:
        name: Test with Maven/PSQL
        script: 
          - cd todobackend
          - mvn test -Dspring.profiles.active=prod -DPOSTGRES_HOST=localhost
        services:
          - postgresdb
                  
    # Build with Maven, Create & Push Docker Images to a Docker Registry
    - step:
        name: Build with Maven, Create & Push Docker Images to a Docker Registry
        script: 
          - cd todobackend
          - mvn -B -DskipTests clean install
          - cd ..
          - cd todoui
          - mvn -B -DskipTests clean install
          - cd .. 
          - docker build -f Dockerfile-todobackend -t $DOCKER_REPOSITORY/todobackend:v$BITBUCKET_BUILD_NUMBER .
          - docker build -f Dockerfile-todoui -t $DOCKER_REPOSITORY/todoui:v$BITBUCKET_BUILD_NUMBER .
          - docker login $DOCKER_REPOSITORY --username $USERNAME --password $PASSWORD
          - docker push $DOCKER_REPOSITORY/todobackend:v$BITBUCKET_BUILD_NUMBER
          - docker push $DOCKER_REPOSITORY/todoui:v$BITBUCKET_BUILD_NUMBER
        services:
          - docker
        caches: 
          - docker
          
    # Deploy Application on K8s
    - step:
        name: Deploy Application on K8s
        script:       
          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_AKS_NAME: 'CICDAKSCluster'
              AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
              KUBECTL_COMMAND: 'apply'
              KUBECTL_ARGUMENTS: '-f configmap.yml'

          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_AKS_NAME: 'CICDAKSCluster'
              AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
              KUBECTL_COMMAND: 'apply'
              KUBECTL_ARGUMENTS: '-f secret.yml'

          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_AKS_NAME: 'CICDAKSCluster'
              AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
              KUBECTL_COMMAND: 'apply'
              KUBECTL_ARGUMENTS: '-f postgres.yml'

          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_AKS_NAME: 'CICDAKSCluster'
              AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
              KUBECTL_COMMAND: 'apply'
              KUBECTL_ARGUMENTS: '-f todobackend.yml'

          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
             AZURE_APP_ID: $AZURE_APP_ID
             AZURE_PASSWORD: $AZURE_PASSWORD
             AZURE_TENANT_ID: $AZURE_TENANT_ID
             AZURE_AKS_NAME: 'CICDAKSCluster'
             AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
             KUBECTL_COMMAND: 'set image'
             KUBECTL_ARGUMENTS: 'deployment/todobackend todobackend=$DOCKER_REPOSITORY/todobackend:v$BITBUCKET_BUILD_NUMBER'

          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
             AZURE_APP_ID: $AZURE_APP_ID
             AZURE_PASSWORD: $AZURE_PASSWORD
             AZURE_TENANT_ID: $AZURE_TENANT_ID
             AZURE_AKS_NAME: 'CICDAKSCluster'
             AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
             KUBECTL_COMMAND: 'apply'
             KUBECTL_ARGUMENTS: '-f todoui.yml'

          - pipe: microsoft/azure-aks-deploy:1.0.1
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_AKS_NAME: 'CICDAKSCluster'
              AZURE_RESOURCE_GROUP: 'CICDResourceGroup'
              KUBECTL_COMMAND: 'set image' 
              KUBECTL_ARGUMENTS: 'deployment/todoui todoui=$DOCKER_REPOSITORY/todoui:v$BITBUCKET_BUILD_NUMBER'
              
definitions: 
  services:
    postgresdb: 
      image: postgres 
      variables: 
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASSWORD  
        POSTGRES_DB: $DB_NAME         


