apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todoui
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
    spec:
      containers:
      - name: todoui
        image: mirna/todoui:v1
---
apiVersion: v1
kind: Service
metadata:
  name: todoui
spec:
  type: LoadBalancer
  ports:
  - port: 8090
  selector:
    app: todoui        
