apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todobackend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: todobackend
      labels:
        app: todobackend
    spec:
      containers:
      - image: mirna/todobackend:1
        name: todobackend
---
apiVersion: v1
kind: Service
metadata:
  name: todobackend
spec:
  type: ClusterIP
  ports:
  - port: 8082
  selector:
    app: todobackend   